github: # Leave blank
patreon: # Leave blank
open_collective: # Leave blank
ko_fi: # Leave blank
tidelift: # Leave blank
community_bridge: # Leave blank
liberapay: # Leave blank
issuehunt: # Leave blank
otechie: # Leave blank
lfx_crowdfunding: # Leave blank

custom: ["https://github.com/Voyend/drag-drop-area-3d/blob/main/DONATIONS.md"]
